'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import type { LayerGroup, Map as LeafletMap, Marker as LeafletMarker } from 'leaflet';
import { routePlans, type RoutePlan, type TransportLeg } from './routes';

type Category = '人文' | '自然' | '自然＋人文' | '演艺' | '主题园区';
type VideoRating = '超级顶' | '顶级' | '人上人' | 'NPC' | '拉';
type Place = {
  id:string; name:string; region:string; category:Category; score:1|2|3|4|5;
  lat:number; lng:number; amapPoi?:string; duration:string; reason:string; tip:string; verdict:string;
  videoRating?:VideoRating; videoTime?:string; videoReview?:string; videoTip?:string;
};
type ViewMode = 'places' | 'routes';

const VIDEO_URL = 'https://www.bilibili.com/video/BV1JXDkByENP/';
const places: Place[] = [
  { id:'henan-museum', name:'河南博物院', region:'郑州', category:'人文', score:4, lat:34.7892878, lng:113.6659927, duration:'3–4小时', verdict:'顺路值得', reason:'用贾湖骨笛、妇好鸮尊、莲鹤方壶快速建立中原文明时间线，是进入河南旅行的好序章。', tip:'国庆票源紧张，只走官方预约；若抢不到，不建议为此改变整条路线。' },
  { id:'only-henan', name:'只有河南·戏剧幻城', region:'郑州', category:'演艺', score:4, lat:34.8001555, lng:113.9938185, duration:'1整天', verdict:'演艺爱好者加分', reason:'21座剧场以土地、粮食与传承讲述河南，沉浸感强，是现代方式理解中原的一次补充。', tip:'它是现代文旅演艺，不是真遗址；不要为它挤掉龙门石窟或三皇寨。' },
  { id:'shangdu', name:'郑州商都遗址博物院', region:'郑州', category:'人文', score:3, lat:34.7475745, lng:113.6806525, duration:'2–3小时', verdict:'考古向备选', reason:'集中展示约3600年前的早商都城，适合对城市起源、夯土城墙和考古学感兴趣的人。', tip:'遗址本身视觉冲击有限，最好听讲解；普通游客可让位给河南博物院。' },
  { id:'yellow-river-park', name:'郑州黄河风景名胜区（黄河文化公园）', region:'郑州', category:'自然＋人文', score:3, lat:34.9475818, lng:113.5170070, duration:'3–4小时', verdict:'返程顺路可选', reason:'在黄河中下游分界处观河，配炎黄二帝巨像与五龙峰景区，是公开线路里常见的“母亲黄河”打卡点。', tip:'园区步行距离长，建议乘园内摆渡；秋冬水量小、滩地裸露，上午光线更好，自驾停山门停车场。' },
  { id:'shaolin', name:'少林寺与塔林', region:'登封', category:'人文', score:5, lat:34.5084042, lng:112.9352133, duration:'3小时', verdict:'经典必到', reason:'禅宗祖庭、历代高僧塔林与功夫文化集中，是理解嵩山佛教文化的核心现场。', tip:'国庆停车与武术表演候场拥挤；门口免费香、开光、算命等主动揽客不要参与。', videoRating:'顶级', videoTime:'00:00:14', videoReview:'视频将嵩山少林景区整体评为“顶级”，认为太室山和少室山各有侧重。', videoTip:'爬山看风景优先少室山；喜欢人文可选太室山，太室山无缆车，建议雨后前往。' },
  { id:'sanhuangzhai', name:'三皇寨·书册崖', region:'登封', category:'自然＋人文', score:5, lat:34.4642849, lng:112.9222448, duration:'3–5小时', verdict:'最合偏好', reason:'少室山褶皱岩层、悬空栈道与书册崖把地质奇观和少林文化真正连成一体。', tip:'认准少林索道；全穿越需提前安排三皇寨出口接车，雨天或大风可能临时关闭。', videoRating:'顶级', videoTime:'00:00:14', videoReview:'视频认为少室山拥有独一无二的地貌，适合以爬山看风景为主的人。', videoTip:'嵩山范围大，建议太室山、少室山二选一，避免把行程排得过满。' },
  { id:'songyang', name:'嵩阳书院', region:'登封', category:'人文', score:4, lat:34.4818247, lng:113.027221, duration:'1–1.5小时', verdict:'安静高质量', reason:'宋代四大书院之一，古柏、院落与理学教育共同构成嵩山的儒家一面。', tip:'规模不大，价值在历史背景而非视觉奇观；建议配讲解。' },
  { id:'zhongyue', name:'中岳庙', region:'登封', category:'人文', score:4, lat:34.459152, lng:113.067687, duration:'1.5–2小时', verdict:'建筑爱好者推荐', reason:'五岳祭祀体系的重要道教建筑群，轴线完整、古树密集，比少林寺清静。', tip:'不要只在中轴线快走，碑刻、古柏和配殿才是细看重点。' },
  { id:'longmen', name:'龙门石窟', region:'洛阳', category:'人文', score:5, lat:34.5571154, lng:112.4707112, duration:'3–5小时', verdict:'全程第一优先', reason:'北魏至唐代石刻艺术的高峰，奉先寺卢舍那大佛、宾阳三洞与万佛洞不可替代。', tip:'国庆必须提前预约；动线部分单向，首次去建议早场，把西山石窟看完整。', videoRating:'顶级', videoTime:'00:01:06', videoReview:'视频肯定其石像数量、质量与皇家营造气势，并提到AR体验；同时认为整体风格丰富度不如云冈石窟。', videoTip:'推荐带讲解，或在现场跟随导游理解造像背景。' },
  { id:'white-horse', name:'白马寺', region:'洛阳', category:'人文', score:4, lat:34.7243309, lng:112.5981357, duration:'2–3小时', verdict:'佛教文化线推荐', reason:'中国早期官办佛寺代表，传统寺院、齐云塔与多国佛殿形成鲜明对照。', tip:'只认官方公众号预约，不购买第三方代售票；尊重宗教场所着装与拍摄规定。' },
  { id:'luoyang-museum', name:'洛阳博物馆', region:'洛阳', category:'人文', score:4, lat:34.6442575, lng:112.4457027, duration:'3小时', verdict:'抢到票就去', reason:'河洛文明、古代石刻、唐三彩和珍宝馆能把洛阳遗址串成完整历史。', tip:'免费但须官方预约，第三方“讲解包门票”风险高；开馆后优先珍宝馆。' },
  { id:'hanwei', name:'汉魏洛阳故城遗址博物馆', region:'洛阳', category:'人文', score:4, lat:34.7239038, lng:112.6088595, duration:'2–3小时', verdict:'白马寺顺路', reason:'以都城考古解释汉魏洛阳，与白马寺相距很近，是洛阳东线最顺手的组合。', tip:'更偏遗址与考古叙事，不是网红拍照型景点；建议先看展再看遗址环境。' },
  { id:'luoyi-ancient-city', name:'洛邑古城', region:'洛阳', category:'主题园区', score:4, lat:34.6821347, lng:112.4784784, duration:'2–3小时', verdict:'夜间体验代表', reason:'以金元古城墙遗址、文峰塔和新潭水系为核心的仿古街区，集中了汉服体验、非遗展示与临水夜景。', tip:'约18:30亮灯后最出片；旺季分时段限流，国庆务必提前一天预约，建议乘地铁或停远处步行进入。' },
  { id:'suitang-city', name:'隋唐洛阳城·明堂天堂与应天门', region:'洛阳', category:'人文', score:4, lat:34.6813400, lng:112.4540900, duration:'半天', verdict:'夜游高性价比', reason:'在隋唐宫城中轴线上复建的明堂、天堂与应天门，用建筑体量和灯光秀还原武周洛阳的都城气势。', tip:'应天门、明堂天堂、九洲池分别售票，可买通票；应天门灯光投影约 19:30 后最佳，白天棚内闷热要带水。' },
  { id:'laojunshan', name:'老君山', region:'栾川', category:'自然＋人文', score:4, lat:33.7677616, lng:111.644368, duration:'1整天', verdict:'风光强·人流风险高', amapPoi:'https://ditu.amap.com/place/B017B01NH7', reason:'十里画屏的花岗岩峰林与金顶道观群辨识度极高，是伏牛山段的自然核心。', tip:'门票不含索道；国庆索道排队和山顶大雾会决定体验，不建议为亮灯夜爬。', videoRating:'人上人', videoTime:'00:04:20', videoReview:'视频认为它网红属性强，是河南旅游代表，但景区较小且相似景观在河南有平替。', videoTip:'最大风险是人流过大导致体验下降；除了山顶，其他景观替代性较强。' },
  { id:'jiguandong', name:'鸡冠洞', region:'栾川', category:'自然', score:3, lat:33.784891, lng:111.5647068, duration:'1.5–2小时', verdict:'天气备选', amapPoi:'https://ditu.amap.com/place/B017B00F6F', reason:'大型喀斯特溶洞，强度低且不受雨、大风和山顶能见度影响。', tip:'人工彩色布光较重，旺季跟团批次可能嘈杂；晴天优先老君山。' },
  { id:'yuntaishan', name:'云台山', region:'焦作', category:'自然', score:5, lat:35.4474908, lng:113.3744344, duration:'建议2天', verdict:'超级顶', videoRating:'超级顶', videoTime:'00:01:46', reason:'视频称其为南太行山水第一，是河南看山水很强的选择。', tip:'夏天体验更好；枯水期部分瀑布可能依赖人工放水。', videoReview:'景色强，但各景点间不断坐车、打卡，整体体验略显零碎。', videoTip:'神农山和青天河在视频中被认为可不专程前往。' },
  { id:'yinxu', name:'殷墟', region:'安阳', category:'人文', score:3, lat:36.1395296, lng:114.3027921, duration:'半天', verdict:'NPC·历史爱好者适配', videoRating:'NPC', videoTime:'00:02:48', reason:'世界文化遗产，人少，适合历史文化与文物爱好者。', tip:'视频认为核心看点集中在博物馆。', videoReview:'即使节假日人流也相对少，可作为偏安静的历史打卡点。', videoTip:'视频提到17:30之后博物馆免费，出发前请再核验最新开放政策。' },
  { id:'hongqiqu', name:'红旗渠', region:'林州', category:'人文', score:1, lat:36.2739732, lng:113.7711675, duration:'半天', verdict:'视频评为“拉”', videoRating:'拉', videoTime:'00:03:16', reason:'视频认为近期水量不足，单独前往的观赏体验有限。', tip:'作者建议可考虑山西长治段的免费路线。', videoReview:'评价重点是“没水”导致景观表现较弱。', videoTip:'水量可能随季节和管理变化，出发前应查询实时情况。' },
  { id:'taihang-grand-canyon', name:'林州太行大峡谷', region:'林州', category:'自然', score:4, lat:36.1460857, lng:113.8847719, duration:'1整天', verdict:'人上人', videoRating:'人上人', videoTime:'00:03:30', reason:'有山有水，视频认为整体达到值得去的水平。', tip:'作者认为山景不如八里沟、水景不如云台山。', videoReview:'作为林州代表性山水景区具备完整体验，但并非同类中的最强项。', videoTip:'如果时间有限，可结合八里沟、云台山的偏好做取舍。' },
  { id:'baiyunshan', name:'白云山', region:'嵩县', category:'自然', score:5, lat:33.7562236, lng:111.9146489, duration:'1–2天', verdict:'顶级', videoRating:'顶级', videoTime:'00:05:08', reason:'视频称其为河南最具代表性的山之一，山水兼备、瀑布较多，主峰玉皇顶海拔2200多米。', tip:'如果在老君山和白云山之间二选一，视频更推荐白云山。', videoReview:'体量、山水组合和自然丰富度是主要加分项。', videoTip:'山地行程强度较高，需结合天气和体力安排。' },
  { id:'qingming-riverside', name:'清明上河园', region:'开封', category:'主题园区', score:3, lat:34.8098675, lng:114.3341353, duration:'半天–1天', verdict:'NPC', videoRating:'NPC', videoTime:'00:05:44', reason:'视频认可其5A景区配套，但认为人造景观可替代性较强。', tip:'作者认为与万岁山区别不大，不必重复安排同类园区。', videoReview:'适合看演艺和主题街区，若更偏自然或真实遗址则优先级不高。', videoTip:'根据演出安排决定停留时间，避免只为建筑布景专程前往。' },
  { id:'kaifeng-drum-tower', name:'开封鼓楼夜市与书店街', region:'开封', category:'人文', score:4, lat:34.7963166, lng:114.3498496, duration:'2–3小时', verdict:'夜生活首选', reason:'鼓楼广场夜市配民国骑楼式书店街，是开封最集中的小吃与市井夜生活现场，灌汤包、炒凉粉、杏仁茶都在此。', tip:'17:30 后开市、19:00–21:00 最挤；往夜市里侧摊位价格更实在，街区禁停，建议打车或骑行抵达。' },
  { id:'baogong-temple', name:'开封包公祠', region:'开封', category:'人文', score:3, lat:34.7937572, lng:114.3332463, duration:'1–1.5小时', verdict:'顺路小景', reason:'包公湖西畔的纪念性祠院，以包拯生平、开封府题名记碑刻讲述宋代司法文化，规模紧凑。', tip:'内容以展陈和碑刻为主，视觉冲击有限；时间紧张时可让位给开封府或清明上河园。' },
  { id:'yaoshan', name:'尧山', region:'鲁山', category:'自然', score:4, lat:33.7608087, lng:112.4989116, duration:'1整天', verdict:'人上人', videoRating:'人上人', videoTime:'00:06:13', reason:'地貌与老君山相近，视频认为水景和奇石更多。', tip:'综合可逛性在视频评价中不如老君山。', videoReview:'适合偏爱山体奇石和水景的人，但不是视频中的河南山岳首选。', videoTip:'可与老君山二选一，减少同质化山景。' },
  { id:'zhongyuan-buddha', name:'中原大佛', region:'鲁山', category:'人文', score:3, lat:33.7751253, lng:112.4509532, duration:'2–3小时', verdict:'NPC·打卡即可', videoRating:'NPC', videoTime:'00:06:58', reason:'视频将其视作单体人造奇观，适合顺路打卡。', tip:'作者认为同类大佛景观特殊性有限，不建议投入过多时间。', videoReview:'核心价值偏视觉尺度与打卡，而非丰富的游览内容。', videoTip:'可与尧山组合，不建议单独安排长途行程。' },
  { id:'longtan-canyon', name:'龙潭大峡谷', region:'新安', category:'自然', score:5, lat:34.9615, lng:111.9878, duration:'3.5–4小时', verdict:'顶级·高性价比', amapPoi:'https://ditu.amap.com/place/B017B01FQ9', videoRating:'顶级', videoTime:'00:07:09', reason:'视频认为山、水、洞等景观丰富，门票只需几十元且游客较少。', tip:'景区经历过破产重组，服务水平不宜期待过高。', videoReview:'高性价比和低人流是突出优势，作者明确表示非常推荐。', videoTip:'视频提示游客正在变多，节假日前往仍建议尽早。' },
  { id:'xixia-dinosaur', name:'西峡恐龙遗迹园', region:'西峡', category:'主题园区', score:1, lat:33.230849, lng:111.680156, duration:'半天', verdict:'视频评为“拉”', amapPoi:'https://www.amap.com/place/B0G3VXEC4B', videoRating:'拉', videoTime:'00:07:55', reason:'视频认为主要是室内游览，整体缺少足够看点。', tip:'如果不是对恐龙主题特别感兴趣，不建议专程前往。', videoReview:'视频给出的评价较低，核心问题是体验内容单一。', videoTip:'亲子或恐龙爱好者可能有不同感受，地图仅忠实记录视频观点。' },
  { id:'laojieling', name:'老界岭', region:'西峡', category:'自然', score:3, lat:33.6417106, lng:111.7635078, duration:'半天–1天', verdict:'NPC', videoRating:'NPC', videoTime:'00:08:08', reason:'视频认为景区体量较小、缺少人文内容。', tip:'作者认为景观不如老君山和尧山。', videoReview:'适合顺路补充，不属于视频强推荐目的地。', videoTip:'若已有老君山或尧山行程，可减少同类型安排。' },
  { id:'chayashan', name:'嵖岈山', region:'遂平', category:'自然', score:4, lat:33.2332753, lng:113.7516731, duration:'1整天', verdict:'人上人', videoRating:'人上人', videoTime:'00:08:27', reason:'典型花岗岩地貌，视频认为奇石景观很有看点。', tip:'视频认为《西游记》主题园区是减分项，并提示灵山部分维护体验较差。', videoReview:'自然奇石是核心优势，主题包装反而削弱体验。', videoTip:'优先游览自然地貌区域，谨慎安排主题园区和维护不足的区域。' },
  { id:'mangdangshan', name:'芒砀山', region:'永城', category:'自然＋人文', score:1, lat:34.15876, lng:116.47095, duration:'半天–1天', verdict:'视频评为“拉”', videoRating:'拉', videoTime:'00:09:08', reason:'以汉文化为主题，但视频认为山体较矮、人造建筑较新且较多。', tip:'作者特别介意山体受采石影响，整体体验评价较低。', videoReview:'历史主题有辨识度，但自然完整性和人工痕迹影响观感。', videoTip:'除非对汉文化主题有明确兴趣，否则不建议专程前往。' },
  { id:'baligou', name:'八里沟', region:'辉县', category:'自然', score:5, lat:35.5534889, lng:113.620077, duration:'1整天', verdict:'超级顶·河南山岳首推', videoRating:'超级顶', videoTime:'00:09:45', reason:'视频称其为南太行代表，天河瀑布等景观突出，体量很大。', tip:'所有子景区（如天界山）都值得去，但必须提前规划线路。', videoReview:'作者表示如果河南只能去一座山，首推八里沟。', videoTip:'体量大，不适合临时随意逛；出发前应确定游览区域和接驳安排。' },
  { id:'baoquan', name:'宝泉旅游度假区', region:'辉县', category:'自然', score:4, lat:35.4644, lng:113.4564, duration:'半天–1天', verdict:'人上人', amapPoi:'https://www.amap.com/place/B0L0DHMW9K', videoRating:'人上人', videoTime:'00:10:31', reason:'“太行第一湾”是视频认为最值得看的核心景观。', tip:'爬山与玩水分开收费且价格偏高，游乐设施多、自然景观相对少。', videoReview:'核心景色好看，但重复看湾的体验较单一，可替代性较强。', videoTip:'明确想看第一湾再去，提前核对分区票价和游玩项目。' },
  { id:'guoliangcun', name:'万仙山·郭亮村挂壁公路', region:'辉县', category:'自然＋人文', score:5, lat:35.7318986, lng:113.5974111, duration:'1整天', verdict:'南太行标志', reason:'村民手工开凿的绝壁长廊挂在红岩崖壁上，配郭亮村、天梯与崖上村落，是南太行最具冲击力的人文自然组合。', tip:'隧道昏暗、车行人混流，靠内侧走并备照明；国庆景交与步行段极易堵，建议山上住一晚不要当天往返郑州。' },
  { id:'jigongshan', name:'鸡公山', region:'信阳', category:'自然', score:3, lat:31.8366249, lng:114.2355213, duration:'1整天', verdict:'NPC', videoRating:'NPC', videoTime:'00:11:06', reason:'视频认为整体景观普通、同类替代较多。', tip:'作者认为夏季避暑体验名不副实，并表示不如南湾湖及河南其他山岳。', videoReview:'作者因个人雪中被困经历保留到NPC档，否则可能会给“拉”。', videoTip:'不要仅凭“避暑”标签安排行程，出发前查看实时气温。' },
  { id:'taihao', name:'太昊伏羲陵', region:'淮阳', category:'人文', score:3, lat:33.7545742, lng:114.8829351, duration:'2–3小时', verdict:'NPC·文化打卡', videoRating:'NPC', videoTime:'00:11:44', reason:'视频建议把它作为始祖信仰与礼制文化场所理解。', tip:'以寺庙、祭祀空间的方式游览，不要期待大型自然景观。', videoReview:'价值主要在始祖文化和仪式空间，适合顺路参观。', videoTip:'尊重祭祀场所秩序，关注当地开放信息。' },
];

const regions = ['全部', ...Array.from(new Set(places.map(p=>p.region)))] as const;
const originalRouteIds = ['henan-museum','shaolin','sanhuangzhai','songyang','white-horse','hanwei','longmen','laojunshan','jiguandong'];

function tLat(x:number,y:number){let r=-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x));r+=(20*Math.sin(6*x*Math.PI)+20*Math.sin(2*x*Math.PI))*2/3;r+=(20*Math.sin(y*Math.PI)+40*Math.sin(y/3*Math.PI))*2/3;r+=(160*Math.sin(y/12*Math.PI)+320*Math.sin(y*Math.PI/30))*2/3;return r}
function tLng(x:number,y:number){let r=300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x));r+=(20*Math.sin(6*x*Math.PI)+20*Math.sin(2*x*Math.PI))*2/3;r+=(20*Math.sin(x*Math.PI)+40*Math.sin(x/3*Math.PI))*2/3;r+=(150*Math.sin(x/12*Math.PI)+300*Math.sin(x/30*Math.PI))*2/3;return r}
function wgsToGcj(lng:number,lat:number){const a=6378245,ee=.006693421622965943;let dLat=tLat(lng-105,lat-35),dLng=tLng(lng-105,lat-35);const rad=lat/180*Math.PI;let magic=Math.sin(rad);magic=1-ee*magic*magic;const root=Math.sqrt(magic);dLat=dLat*180/(a*(1-ee)/(magic*root)*Math.PI);dLng=dLng*180/(a/root*Math.cos(rad)*Math.PI);return [lng+dLng,lat+dLat]}
function amapUrl(p:Place){if(p.amapPoi)return p.amapPoi;const [lng,lat]=wgsToGcj(p.lng,p.lat);return `https://uri.amap.com/marker?position=${lng.toFixed(6)},${lat.toFixed(6)}&name=${encodeURIComponent(p.name)}&src=henan-trip-map&coordinate=gaode&callnative=1`}
function amapSearch(name:string){return `https://uri.amap.com/search?keyword=${encodeURIComponent(name)}&city=%E6%B2%B3%E5%8D%97&src=henan-trip-map&callnative=1`}
function videoUrl(time?:string){if(!time)return VIDEO_URL;const [h,m,s]=time.split(':').map(Number);return `${VIDEO_URL}?t=${h*3600+m*60+s}`}
function Stars({score}:{score:number}){return <span className="stars" aria-label={`推荐值 ${score} 分`}>{'★'.repeat(score)}<i>{'★'.repeat(5-score)}</i></span>}
function modeIcon(mode: TransportLeg['mode']){return mode==='高铁'?'🚄':mode==='景区交通'?'🚌':mode==='步行'?'🥾':'🚗'}
function routePlaceIds(route:RoutePlan,day:number|'all'){const days=day==='all'?route.itinerary:route.itinerary.filter(item=>item.day===day);return Array.from(new Set(days.flatMap(item=>item.placeIds)))}
const cityCoords:Record<string,[number,number]>={郑州:[34.75,113.62],登封:[34.46,113.04],洛阳:[34.62,112.45],新安:[34.73,112.15],嵩县:[34.13,112.09],栾川:[33.79,111.62],焦作:[35.22,113.24],辉县:[35.46,113.80],修武:[35.22,113.44],开封:[34.7971,114.3073],中牟:[34.7189,113.9762]};
function dayCoordinate(day:RoutePlan['itinerary'][number]):[number,number]{const dayPlaces=day.placeIds.map(id=>places.find(place=>place.id===id)).filter(Boolean) as Place[];if(dayPlaces.length)return [dayPlaces.reduce((sum,p)=>sum+p.lat,0)/dayPlaces.length,dayPlaces.reduce((sum,p)=>sum+p.lng,0)/dayPlaces.length];const candidates=day.region.split('/').map(name=>name.trim()).reverse();const city=candidates.find(name=>cityCoords[name]);return city?cityCoords[city]:[34.35,113.1]}
function placeImage(id:string){return `/places/${id}.jpg`}
function placePreviewHtml(place:Place){return `<div class="map-preview"><img src="${placeImage(place.id)}" alt="${place.name}"/><div><b>${place.name}</b><span>${place.region} · ${place.category}</span><small>${place.score}分 · ${place.duration}</small></div></div>`}
function dayPreviewHtml(route:RoutePlan,day:RoutePlan['itinerary'][number]){const dayPlaces=day.placeIds.map(id=>places.find(place=>place.id===id)).filter(Boolean) as Place[];const photos=dayPlaces.length?dayPlaces.map(place=>`<figure><img src="${placeImage(place.id)}" alt="${place.name}"/><figcaption>${place.name}</figcaption></figure>`).join(''):`<div class="route-preview-empty">交通与休整日</div>`;return `<div class="route-preview"><header><b>D${day.day} · ${day.title}</b><span>${day.region}</span></header><div class="route-preview-grid count-${Math.min(dayPlaces.length,3)}">${photos}</div><small>住 ${day.stay}</small></div>`}
function transitionDuration(route:RoutePlan,day:number){const info=route.itinerary.find(item=>item.day===day);const leg=info?.legs[0];return leg?(leg.holiday||leg.normal):''}
function dayNodeLabel(day:RoutePlan['itinerary'][number]){const names=day.placeIds.map(id=>places.find(place=>place.id===id)?.name).filter(Boolean) as string[];const labels=names.length?names:[day.region];return `<div class="route-day-label">${labels.map(name=>`<span>${name}</span>`).join('')}</div>`}

export default function Home(){
  const mapNode=useRef<HTMLDivElement>(null), mapRef=useRef<LeafletMap|null>(null), markersRef=useRef<Map<string,LeafletMarker>>(new Map()), routeLayerRef=useRef<LayerGroup|null>(null);
  const [viewMode,setViewMode]=useState<ViewMode>('places');
  const [region,setRegion]=useState<string>('全部'),[activeId,setActiveId]=useState('longmen'),[mapReady,setMapReady]=useState(false);
  const [routeDays,setRouteDays]=useState<5|6|7>(7),[activeRouteId,setActiveRouteId]=useState('route-7b'),[activeDay,setActiveDay]=useState<number|'all'>('all');
  const visible=useMemo(()=>region==='全部'?places:places.filter(p=>p.region===region),[region]);
  const active=places.find(p=>p.id===activeId)??places[0];
  const routeOptions=useMemo(()=>routePlans.filter(route=>route.days===routeDays),[routeDays]);
  const activeRoute=routePlans.find(route=>route.id===activeRouteId)??routePlans[5];
  const selectedDay=activeDay==='all'?null:activeRoute.itinerary.find(day=>day.day===activeDay)??null;
  const selectedPlaceIds=useMemo(()=>routePlaceIds(activeRoute,activeDay),[activeRoute,activeDay]);

  useEffect(()=>{if(!mapNode.current||mapRef.current)return;let cancelled=false;import('leaflet').then(L=>{if(cancelled||!mapNode.current||mapRef.current)return;const map=L.map(mapNode.current,{zoomControl:false}).setView([34.35,113.1],7);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);L.polyline(originalRouteIds.map(id=>{const p=places.find(x=>x.id===id)!;return [p.lat,p.lng] as [number,number]}),{color:'#d97842',weight:3,opacity:.55,dashArray:'8 10',className:'original-route-line'}).addTo(map);places.forEach(p=>{const icon=L.divIcon({className:'custom-marker-wrap',html:`<div class="custom-marker score-${p.score}"><span>${p.score}</span></div>`,iconSize:[36,44],iconAnchor:[18,40]});const marker=L.marker([p.lat,p.lng],{icon,title:p.name}).addTo(map);marker.bindTooltip(placePreviewHtml(p),{direction:'top',offset:[0,-34],opacity:1,className:'photo-tooltip'});marker.on('click',()=>setActiveId(p.id));markersRef.current.set(p.id,marker)});mapRef.current=map;setMapReady(true)});return()=>{cancelled=true}},[]);

  useEffect(()=>{const map=mapRef.current;if(!map||!mapReady||viewMode!=='places')return;markersRef.current.forEach(marker=>{marker.setOpacity(1);marker.getElement()?.style.removeProperty('pointer-events')});if(region==='全部')map.flyTo([34.35,113.1],7,{duration:.8});else import('leaflet').then(L=>{const group=places.filter(p=>p.region===region);map.fitBounds(L.latLngBounds(group.map(p=>[p.lat,p.lng])),{padding:[70,70],maxZoom:11})})},[region,mapReady,viewMode]);

  useEffect(()=>{const map=mapRef.current;if(!map||!mapReady)return;routeLayerRef.current?.remove();routeLayerRef.current=null;if(viewMode!=='routes'){markersRef.current.forEach(marker=>{marker.setOpacity(1);marker.getElement()?.style.removeProperty('pointer-events')});return}import('leaflet').then(L=>{if(!mapRef.current)return;const layer=L.layerGroup().addTo(mapRef.current);routeLayerRef.current=layer;const allRouteIds=routePlaceIds(activeRoute,'all');markersRef.current.forEach(marker=>{marker.setOpacity(0);marker.setZIndexOffset(0);marker.getElement()?.style.setProperty('pointer-events','none')});const shown=activeDay==='all'?activeRoute.itinerary:activeRoute.itinerary.filter(item=>item.day===activeDay);const coords=shown.map(dayCoordinate);if(coords.length>1){L.polyline(coords,{color:activeRoute.color,weight:5,opacity:.9,lineCap:'round',lineJoin:'round'}).addTo(layer);shown.slice(1).forEach((item,index)=>{const previous=coords[index],current=coords[index+1];const duration=transitionDuration(activeRoute,item.day);if(!duration)return;const middle:[number,number]=[(previous[0]+current[0])/2,(previous[1]+current[1])/2];L.marker(middle,{interactive:false,icon:L.divIcon({className:'duration-label-wrap',html:`<div class="duration-label">${duration}</div>`,iconAnchor:[50,12]})}).addTo(layer)})}shown.forEach((day,index)=>{const routeMarker=L.marker(coords[index],{interactive:true,icon:L.divIcon({className:'route-day-wrap',html:`<div class="route-day-pin" style="--route-color:${activeRoute.color}">D${day.day}</div>${dayNodeLabel(day)}`,iconSize:[140,70],iconAnchor:[70,14]})}).addTo(layer);routeMarker.bindTooltip(dayPreviewHtml(activeRoute,day),{direction:'top',offset:[0,-18],opacity:1,className:'route-photo-tooltip'})});if(coords.length===1)mapRef.current.flyTo(coords[0],11,{duration:.7});else if(coords.length>1)mapRef.current.fitBounds(L.latLngBounds(coords),{padding:[90,90],maxZoom:10});else{const allCoords=allRouteIds.map(id=>{const p=places.find(place=>place.id===id)!;return [p.lat,p.lng] as [number,number]});if(allCoords.length)mapRef.current.fitBounds(L.latLngBounds(allCoords),{padding:[90,90],maxZoom:9})}})},[viewMode,mapReady,activeRoute,activeDay,selectedPlaceIds]);

  function focus(p:Place){setActiveId(p.id);mapRef.current?.flyTo([p.lat,p.lng],12,{duration:.75});markersRef.current.get(p.id)?.openTooltip()}
  function chooseDuration(days:5|6|7){setRouteDays(days);const next=routePlans.find(route=>route.days===days&&route.featured)??routePlans.find(route=>route.days===days)!;setActiveRouteId(next.id);setActiveDay('all')}
  function chooseRoute(route:RoutePlan){setActiveRouteId(route.id);setActiveDay('all')}
  function switchView(mode:ViewMode){setViewMode(mode);if(mode==='routes'){setActiveDay('all')}else{routeLayerRef.current?.remove();routeLayerRef.current=null}}

  return <main className={`site-shell ${viewMode==='routes'?'route-mode':''}`}>
    <header className="topbar">
      <div><p className="eyebrow">HENAN · 2026 GOLDEN WEEK</p><h1>河南双人旅行地图</h1></div>
      <div className="view-switch" role="tablist" aria-label="地图视图">
        <button role="tab" aria-selected={viewMode==='places'} className={viewMode==='places'?'active':''} onClick={()=>switchView('places')}><span>地点</span>景点地图</button>
        <button role="tab" aria-selected={viewMode==='routes'} className={viewMode==='routes'?'active':''} onClick={()=>switchView('routes')}><span>路线</span>行程规划</button>
      </div>
      <div className="route-summary"><span>{viewMode==='places'?'地图内容':'已规划路线'}</span><strong>{viewMode==='places'?'36 处地点':'5 / 6 / 7 日 · 共 9 条'}</strong></div>
    </header>

    {viewMode==='places'?<section className="toolbar" aria-label="地区筛选"><div className="region-tabs">{regions.map(r=><button key={r} className={region===r?'active':''} onClick={()=>setRegion(r)}>{r}<small>{r==='全部'?places.length:places.filter(p=>p.region===r).length}</small></button>)}</div><div className="legend"><span><b className="legend-dot top"/>5分强推</span><span><b className="legend-dot good"/>4分推荐</span><span><b className="legend-dot optional"/>3分顺路</span><span><b className="legend-dot avoid"/>1分慎选</span></div></section>:
      <section className="toolbar route-toolbar" aria-label="路线天数筛选"><div className="duration-tabs">{([5,6,7] as const).map(days=><button key={days} className={routeDays===days?'active':''} onClick={()=>chooseDuration(days)}><strong>{days}</strong><span>日路线</span></button>)}</div><p><b>国庆规划口径</b> 常规车程＋拥堵缓冲；实时路况请从高德入口复核。</p></section>}

    <section className="map-layout">
      {viewMode==='places'?<aside className="place-list"><div className="list-head"><strong>{region==='全部'?'全部地点':`${region}地点`}</strong><span>{visible.length}处</span></div><div className="cards-scroll">{visible.map(p=><button key={p.id} className={`place-row ${activeId===p.id?'selected':''}`} onClick={()=>focus(p)}><span className={`score-badge score-${p.score}`}>{p.score}</span><span className="place-copy"><strong>{p.name}</strong><small>{p.category} · {p.duration}{p.videoRating?` · 视频：${p.videoRating}`:''}</small></span><span className="row-arrow">↗</span></button>)}</div></aside>:
        <aside className="route-list"><div className="list-head"><div><strong>{routeDays} 日方案</strong><small>选择一条路线查看每日安排</small></div><span>{routeOptions.length}条</span></div><div className="cards-scroll route-cards">{routeOptions.map(route=><button key={route.id} className={`route-card ${activeRoute.id===route.id?'selected':''}`} style={{'--route-color':route.color} as React.CSSProperties} onClick={()=>chooseRoute(route)}><div className="route-card-head"><span className="route-code">{route.code}</span>{route.featured&&<span className="recommend-chip">首选</span>}<span className={`pace pace-${route.pace}`}>{route.pace}</span></div><strong>{route.name}</strong><small>{route.theme} · {route.cities.join(' → ')}</small><p>{route.summary}</p><div className="route-metrics"><span><b>{route.fiveScoreIds.length}</b> 个5分点</span><span><b>{route.hotelMoves}</b> 次换酒店</span></div><div className="route-card-foot"><span>{route.longestLeg}</span><b>查看路线 ↗</b></div></button>)}</div></aside>}

      <div className="map-stage">
        <div ref={mapNode} className="map-canvas" aria-label="河南旅行互动地图"/>
        <div className="map-note"><span>{viewMode==='places'?'虚线为原建议动线':`${activeRoute.code} · ${activeRoute.cities.join(' → ')}`}</span><b>{viewMode==='places'?'点击数字标记查看详情':'点击 D1–D7 聚焦当天'}</b></div>
        {viewMode==='places'?<PlaceDetail place={active}/>:
          <RouteDetail route={activeRoute} activeDay={activeDay} setActiveDay={setActiveDay} focus={focus} selectedDay={selectedDay}/>} 
      </div>
    </section>
    <footer><span>{viewMode==='places'?'视频档位为作者主观评价；地图分数映射：超级顶/顶级=5，人上人=4，NPC=3，拉=1。':'车程为规划口径，不代表国庆实时路况；出发前请复核车次、预约、天气与索道。'}</span>{viewMode==='places'?<a href={VIDEO_URL} target="_blank" rel="noreferrer">来源：B站《河南省5A景区从夯到拉》</a>:<span>2026 国庆 · 上海出发</span>}</footer>
  </main>
}

function PlaceDetail({place}:{place:Place}){return <article className="detail-card" key={place.id}><div className="detail-topline"><span className="region-chip">{place.region} · {place.category}</span><span className="verdict">{place.verdict}</span></div><div className="title-row"><div><h2>{place.name}</h2><Stars score={place.score}/></div><div className={`big-score score-${place.score}`}><strong>{place.score}</strong><span>/ 5</span></div></div><p className="coordinates">WGS84 {place.lat.toFixed(5)}, {place.lng.toFixed(5)}</p><p className="reason">{place.reason}</p>{place.videoRating&&<div className="video-review"><a href={videoUrl(place.videoTime)} target="_blank" rel="noreferrer">视频评价：<strong>{place.videoRating}</strong> · {place.videoTime} ↗</a><p>{place.videoReview}</p>{place.videoTip&&<small>{place.videoTip}</small>}</div>}<div className="tip"><span>旅行提醒</span><p>{place.tip}</p></div><div className="detail-actions"><span>建议停留 <strong>{place.duration}</strong></span><a href={amapUrl(place)} target="_blank" rel="noreferrer">高德地图查看 / 导航 <b>↗</b></a></div></article>}

function RouteDetail({route,activeDay,setActiveDay,focus,selectedDay}:{route:RoutePlan;activeDay:number|'all';setActiveDay:(day:number|'all')=>void;focus:(place:Place)=>void;selectedDay:RoutePlan['itinerary'][number]|null}){
  const days=selectedDay?[selectedDay]:route.itinerary;
  return <article className="route-detail-card" style={{'--route-color':route.color} as React.CSSProperties}>
    <div className="route-detail-heading"><div><div className="route-kicker"><span>{route.code}</span>{route.featured&&<b>推荐方案</b>} · {route.theme}</div><h2>{route.name}</h2><p>{route.summary}</p></div><div className="route-score"><strong>{route.fiveScoreIds.length}</strong><span>个 5 分点</span></div></div>
    <div className="city-chain">{route.cities.map((city,index)=><span key={city}>{index>0&&<i>→</i>}<b>{city}</b></span>)}</div>
    <div className="day-tabs" role="tablist"><button className={activeDay==='all'?'active':''} onClick={()=>setActiveDay('all')}>全程</button>{route.itinerary.map(day=><button key={day.day} className={activeDay===day.day?'active':''} onClick={()=>setActiveDay(day.day)}>D{day.day}</button>)}</div>
    <div className="itinerary-scroll">{days.map(day=><section className="day-card" key={day.day}><div className="day-index">D{day.day}</div><div className="day-content"><div className="day-title"><div><strong>{day.title}</strong><small>{day.region} · 住 {day.stay}</small></div>{day.placeIds.length>0&&<span>{day.placeIds.length} 个景点</span>}</div><p>{day.summary}</p>{day.placeIds.length>0&&<div className="day-places">{day.placeIds.map(id=>{const p=places.find(item=>item.id===id);return p?<button key={id} onClick={()=>focus(p)}><span className={`mini-score score-${p.score}`}>{p.score}</span>{p.name}<b>定位 ↗</b></button>:null})}</div>}{day.legs.length>0&&<div className="transport-list">{day.legs.map((leg,index)=><div className="transport-leg" key={`${leg.from}-${leg.to}-${index}`}><span className="mode-icon">{modeIcon(leg.mode)}</span><div><strong>{leg.from}<i>→</i>{leg.to}</strong><p><b>{leg.mode}</b> · {leg.normal}{leg.holiday&&<em>国庆：{leg.holiday}</em>}</p>{leg.note&&<small>{leg.note}</small>}</div><a href={amapSearch(leg.to)} target="_blank" rel="noreferrer" aria-label={`在高德地图查看${leg.to}`}>高德 ↗</a></div>)}</div>}</div></section>)}</div>
  </article>
}
